### ISSUE TITLE
Front end editing

### ISSUE THREAD

**Issue by rachelwalraven** [conconnl/joomla-basictemplate#11]
Ik heb een probleem ontdekt met de frontend editing en de template. Het werkt niet.
Bij gebruik van TinyMCE wordt alleen de broncode weer gegeven en je kan niet opslaan. Met JCE krijg je wel de editor te zien, maar ook hier kan je niet opslaan. 
In de inspector krijg ik de volgende foutmeldingen te zien:

```
Uncaught ReferenceError: Joomla is not defined
    at keepalive.js:1
chosen.jquery.min.js:1 Uncaught ReferenceError: jQuery is not defined
    at chosen.jquery.min.js:1
    at chosen.jquery.min.js:2
ajax-chosen.min.js:17 Uncaught ReferenceError: jQuery is not defined
    at ajax-chosen.min.js:17
sponsoring?view=form&layout=edit&a_id=14&return=aHR0cDovL2xvY2FsaG9zdC90b29ua3Vuc3QvaW5kZXgucGhwL3Nwb25zb3Jpbmcvc3BvbnNvcmluZz9hX2lkPTE0:85 Uncaught ReferenceError: Joomla is not defined
    at sponsoring?view=form&layout=edit&a_id=14&return=aHR0cDovL2xvY2FsaG9zdC90b29ua3Vuc3QvaW5kZXgucGhwL3Nwb25zb3Jpbmcvc3BvbnNvcmluZz9hX2lkPTE0:85
sponsoring?view=form&layout=edit&a_id=14&return=aHR0cDovL2xvY2FsaG9zdC90b29ua3Vuc3QvaW5kZXgucGhwL3Nwb25zb3Jpbmcvc3BvbnNvcmluZz9hX2lkPTE0:70 Uncaught TypeError: $(...).find(...).chosen is not a function
    at initChosen (sponsoring?view=form&layout=edit&a_id=14&return=aHR0cDovL2xvY2FsaG9zdC90b29ua3Vuc3QvaW5kZXgucGhwL3Nwb25zb3Jpbmcvc3BvbnNvcmluZz9hX2lkPTE0:70)
    at HTMLDocument.<anonymous> (sponsoring?view=form&layout=edit&a_id=14&return=aHR0cDovL2xvY2FsaG9zdC90b29ua3Vuc3QvaW5kZXgucGhwL3Nwb25zb3Jpbmcvc3BvbnNvcmluZz9hX2lkPTE0:64)
    at i (jquery.min.js?2a0e5978101fa1963e8e33323f8cb066:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?2a0e5978101fa1963e8e33323f8cb066:2)
    at Function.ready (jquery.min.js?2a0e5978101fa1963e8e33323f8cb066:2)
    at HTMLDocument.K (jquery.min.js?2a0e5978101fa1963e8e33323f8cb066:2)
sponsoring?view=form&layout=edit&a_id=14&return=aHR0cDovL2xvY2FsaG9zdC90b29ua3Vuc3QvaW5kZXgucGhwL3Nwb25zb3Jpbmcvc3BvbnNvcmluZz9hX2lkPTE0:564 Uncaught ReferenceError: Joomla is not defined
    at HTMLButtonElement.onclick (sponsoring?view=form&layout=edit&a_id=14&return=aHR0cDovL2xvY2FsaG9zdC90b29ua3Vuc3QvaW5kZXgucGhwL3Nwb25zb3Jpbmcvc3BvbnNvcmluZz9hX2lkPTE0:564)
```
Dit is met de blanco template (ook getest in een blanco Joomla installatie). 

Iemand enig idee hoe dit op te lossen?

**Comment by Joomill** [comment]
Ik dacht het op te lossen met een override, maar dat werkte niet zoals in mijn eigen versie van de template.

In de helper.php heb ik de volgende regels uitgezet. Dan werkt het wel.
        // unset($doc->_scripts[$doc->baseurl . '/media/system/js/validate.js']);
        // unset($doc->_scripts[$doc->baseurl . '/media/system/js/core.js']);
        // unset($doc->_scripts[$doc->baseurl . '/media/jui/js/jquery.min.js']);

Als er een betere oplossing is dan hoor ik dat ook graag.

**Comment by rachelwalraven** [comment]
Bij mij werkt deze oplossing.
Ik gok alleen dat deze niet voor niets ge-unset zijn?

**Comment by conconnl** [comment]
Jeroen en ik zullen hier eens goed naar kijken.

**Comment by hans2103** [comment]
@rachelwalraven wat je zou kunnen doen.... om er zeker van te zijn dat Fronted Edit werkt is aldaar omschakelen naar Protostar. Daarmee laat je de styling van Frontend Edit compleet los van de styling van de door jouw geoptimaliseerde template.

**Comment by hans2103** [comment]
een positieve reactie van @rachelwalraven op mijn voorstel. Issue kan gesloten worden.
