### ISSUE TITLE
Implement certain OpenGraph meta properties

### ISSUE THREAD

**Issue by conconnl** [conconnl/joomla-basictemplate#16]
```
	static public function getSiteDesc()
	{
		return Factory::getDocument()->getDescription();
	}
```
```
	static public function getPageTitle()
	{
		return Factory::getDocument()->getTitle();
	}
```
```
	static public function getLogoFile()
	{
		return Factory::getApplication()->getTemplate(true)->params->get('logoFile');
	}
```

`$doc->setMetaData('og:title', self::getPageTitle(), 'property');`
`$doc->setMetaData('og:description', self::getSiteDesc(), 'property');`
`$doc->setMetaData('og:image',JUri::root() . self::getLogoFile(), 'property');`

**Comment by hans2103** [comment]
Ik zou dit niet adviseren. 
Het is beter om dit soort zaken over te laten aan een separate plugin en niet in de template te verwerken. En heul toevallig heb ik een dergelijke plugin al gemaakt: https://github.com/hans2103/pkg_SocialMetaTags/

PR met verbeteringen, zoals implementatie bij andere componenten dan com_content is welkom.

**Comment by conconnl** [comment]
Dankje.
Ik had bewust dit issue aangemaakt, met het idee.
Vooral ook om meningen te horen.

Ik sluit het issue, dan hebben wel een registratie als ooit iemand erom vraagt.
