### ISSUE TITLE
Na installatie is de template niet te vinden

### ISSUE THREAD

**Issue by hvdmeer** [conconnl/joomla-basictemplate#19]
Ik heb zojuist een verse download van deze template gedaan in een Joomla installatie (3.8.7 -> 3.8.10) op XAMPP 7.1.3. Het installeren gaat zonder problemen maar als ik daarna bij de templates kijk staat hij er nie tussen. Na een Discover en een uitloggen, inloggen is de template nog steeds niet te vinden. 

Iemand anders hier ook last van?

**Comment by conconnl** [comment]
Nergens gemerkt en gezien. 
Ik zal je toegang geven tot de nieuwe variant met heel veel meer opties. 
Kun je die eventueel testen, des te meer tester, des te sneller we hem kunnen verspreiden.
