### ISSUE TITLE
ipad is missing the $

### ISSUE THREAD

**Issue by allrude** [conconnl/joomla-basictemplate#4]
[fix] added missing $

        if( $iPod || $iPhone || iPad ){
        if( $iPod || $iPhone || $iPad ){

**Comment by conconnl** [comment]
Dankje, heb het aangepast.
Als je meer aanpassingen, toevoegingen of verbeteringen heb hoor ik het graag.
Hoe mooier het wordt des te meer Joomla! gebruikers kunnen het gebruiken.
